// ENV DEFAULT CONFIG
export const ENV_SERVER_PORT = 'SERVER_PORT';

// ENV SECURITY
export const ENV_SECURITY_JWT_EXPIRE = 'SECURITY_JWT_EXPIRE';
export const ENV_SECURITY_JWT_ISSUER = 'SECURITY_JWT_ISSUER';
export const ENV_SECURITY_RSA_AUTH_PATH = 'SECURITY_RSA_AUTH_PATH';
export const ENV_SECURITY_RSA_BITLENGTH = 'SECURITY_RSA_BITLENGTH';
export const ENV_SECURITY_RSA_PASSPHRASE = 'SECURITY_RSA_PASSPHRASE';

// ENV STORAGE
export const ENV_STORAGE_PATH = 'STORAGE_PATH';
