name: Radoti Image Build
on:
  push:
    branches: [ create-compatible-with-docker ]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        docker build -t radoti:latest .
