name: NestJS Setup
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t github/radoti:latest .
      - name: Run by image
        run: |
          docker run -d github-radoti
