name: NestJS Setup
on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn
      - name: Setup
        run: |
          yarn setup
      - name: Build
        run: |
          yarn build
      - name: Generate keys and print keys
        run: |
          yarn start
          cat .radoti-auth/publicKey.pem
          cat .radoti-auth/privateKey.pem
          cat .radoti-auth/credentials-claim
